### ISSUE TITLE
Versión 3 de Colab

### ISSUE THREAD

**Issue by aletscn** [Ignacio-Ibarra/NLP-Disasters#3]
Hola chicos, 
Les cuento que estoy momentaneamente sin celular.
Acabo de subir la última versión que hice del Colab. Les paso a comentar las modificaciones por secciones:
**Plots**
Aumenté el tamaño de letra

**Primer análisis**
-a los elementos null se les asigna 'no_location', 'no_keyword'
-Se analiza la columna 'location' para verificar que la mayoria de los elementos tienen una única ocurrencia (85%) y por eso no vamos a usarla en el análisis exploratorio.

**Cleaning de tweets repetidos**
- Todos los tweets repetidos con targets contradictorios fueron eliminados
- Se generó un nuevo DF (train_no_duplicates): todos los 'text' que aparecen repetidos (que no tienen target contradictorio) fueron eliminados salvo la primera ocurrencia. Antes de removerlos, se agregó una columna que aclara cuántas veces se repite ese texto. Luego se trabaja solo con train_no_duplicates.
-Se eliminan mentions y urls (tmb & y un simbolo raro que creo que es un emoji) , se vuelve a repetir el analisis de tweets repetidos con targets contradictorios.
-Elimino signos de puntuación, todo esto se asigna a una nueva columna 'text_clean'
-Se repite el mismo análisis de tweets repetidos -contradictorios y se eliminan los contradictorios

**Eliminación de stopwords**
Se genera nueva columna con los textos sin stopword (text_clean_no_sw)

**Análisis de características de tweets**
Agregué que me cuente la cantidad de caracteres/palabras para 'text', 'text_clean', 'text_clean_no_sw'
Ver que cuando calculo la correlación, para las variables de 'text_clean_no_sw' da más alto

**Wordclouds**
Se generan wordclouds para ambos targets
Para verlo:
descargar la imagen que subí a github
hacer Run de uploaded= files.upload(), subir esa imagen, correr el resto
debería darles wordclouds con la forma del logo de twitter (quedaba lindo...je)

**N-grams**
Finalmente hice Ngramas (N=1,2,3) para cada target.

Creo que faltarían :
visualizaciones comparando los top Ngramas (podría ser parecido al del análisis de los keywords)
visualizaciones de las características de tweets

Se les ocurre algo más?

**Comment by Ignacio-Ibarra** [comment]
Ale, agregué un cuadro de comparación de unigramas que habría que ver si sirve para graficar, lo hice haciendo inner. 
Además hice un análisis sobre las clases (sub-clases en realidad) de palabras. Está muy piola solo falta graficar ahí.
